Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Trasportistas_vista.Models;

namespace Trasportistas_vista.Controllers
{
    public class ClientesController : Controller
    {
        private readonly BD_TRASPORTISTASContext _context;

        public ClientesController(BD_TRASPORTISTASContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
              return _context.Clientes != null ? 
                          View(await _context.Clientes.ToListAsync()) :
                          Problem("Entity set 'BD_TRASPORTISTASContext.Clientes'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Codigo,Nombre,FechaNacimiento,Identificacion")] Cliente cliente)
        {
            cliente.Codigo = ClienteTop();
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Codigo,Nombre,FechaNacimiento,Identificacion")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'BD_TRASPORTISTASContext.Clientes'  is null.");
            }
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
          return (_context.Clientes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        private string ClienteTop()
        {
            var top = (_context.Clientes.OrderByDescending(u => u.Id).Take(1).FirstOrDefault());
            if (top == null)
            {
                return "00001";
            }
            var id = top.Id+1;
            return id.ToString().PadLeft(5, '0');
        }
    }
}

Controllers/TrasportistasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Trasportistas_vista.Models;

namespace Trasportistas_vista.Controllers
{
    public class TrasportistasController : Controller
    {
        // Scaffold-DbContext "Server=.;Database=BD_TRASPORTISTAS;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
        // Scaffold-DbContext "Server=.;Database=BD_TRASPORTISTAS;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -tcliente -f
        private readonly BD_TRASPORTISTASContext _context;

        public TrasportistasController(BD_TRASPORTISTASContext context)
        {
            _context = context;
        }

        // GET: Trasportistums
        public async Task<IActionResult> Index()
        {
            return _context.Trasportista != null ?
                        View(await _context.Trasportista.ToListAsync()) :
                        Problem("Entity set 'BD_TRASPORTISTASContext.Trasportista'  is null.");
        }

        // GET: Trasportistums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trasportista == null)
            {
                return NotFound();
            }

            var trasportistum = await _context.Trasportista
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trasportistum == null)
            {
                return NotFound();
            }

            return View(trasportistum);
        }

        // GET: Trasportistums/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trasportistums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Codigo,Nombre")] Trasportistum trasportistum)
        {
            trasportistum.Codigo = TrasportistumTop();
            if (ModelState.IsValid)
            {
                _context.Add(trasportistum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trasportistum);
        }

        // GET: Trasportistums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trasportista == null)
            {
                return NotFound();
            }

            var trasportistum = await _context.Trasportista.FindAsync(id);
            if (trasportistum == null)
            {
                return NotFound();
            }
            return View(trasportistum);
        }

        // POST: Trasportistums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Codigo,Nombre")] Trasportistum trasportistum)
        {
            if (id != trasportistum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trasportistum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrasportistumExists(trasportistum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trasportistum);
        }

        // GET: Trasportistums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trasportista == null)
            {
                return NotFound();
            }

            var trasportistum = await _context.Trasportista
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trasportistum == null)
            {
                return NotFound();
            }

            return View(trasportistum);
        }

        // POST: Trasportistums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trasportista == null)
            {
                return Problem("Entity set 'BD_TRASPORTISTASContext.Trasportista'  is null.");
            }
            var trasportistum = await _context.Trasportista.FindAsync(id);
            if (trasportistum != null)
            {
                _context.Trasportista.Remove(trasportistum);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrasportistumExists(int id)
        {
            return (_context.Trasportista?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private string TrasportistumTop()
        {
            var top = (_context.Trasportista.OrderByDescending(u => u.Id).Take(1).FirstOrDefault());
            if (top == null)
            {
                return "001";
            }
            var id = top.Id + 1;
            return id.ToString().PadLeft(3, '0');
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trasportistas_vista</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Trasportistas_vista.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trasportistas_vista</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trasportistas" asp-action="Index">Trasportistas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArticuloCustodias" asp-action="Index">Articulos</a>
                        </li>
                           <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Reportes" asp-action="Clientes">Reportes de clientes</a>
                        </li>
                        </li>
                           <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Reportes" asp-action="Articulos">Reportes de articulos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Trasportistas_vista - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>